version: "3.8"

services:
  dify-adapter:
    build: .
    ports:
      - "8080:8080"
    environment:
      DIFY_BASE_URL: ${DIFY_BASE_URL:-http://host.docker.internal/v1}
      DIFY_AGENTS: |
        {
          "company-paper": {
            "key": "${DIFY_AGENT_API_KEY_ONE_COMPANY_PAPER}",
            "type": "agent"
          },
          "market-research": {
            "key": "${DIFY_AGENT_API_KEY_MAKERT_RESEARCH}",
            "type": "workflow"
          },
          "meeting-bot": {
            "key": "${DIFY_AGENT_API_KEY_CHATBOT_MEETING}",
            "type": "chat"
          },
          "code-convert": {
            "key": "${DIFY_AGENT_API_KEY_COMPLETION_CODE_CONVERT}",
            "type": "completion"
          }
        }
    restart: unless-stopped
